// The story is a list of stops. Each stop's `path` is the cinematic that plays
// when travelling from the previous stop to it. Going backwards replays that
// path in reverse (as a VHS rewind).

const hop = (x, L) => ({ type: 'hop', x, L });
const hops = (x, from, to) => {
  const out = [];
  const dir = Math.sign(to - from);
  for (let L = from + dir; dir > 0 ? L <= to : L >= to; L += dir) out.push(hop(x, L));
  return out;
};
const drive = (x, L, o = {}) => ({ type: 'move', x, L, dur: 1, ...o });
const jump = (x, L, o = {}) => ({ type: 'move', x, L, dur: 0.8, h: 1, ease: 'linear', ...o });
const mount = (name) => ({ type: 'mount', name });
const dismount = (name) => ({ type: 'dismount', name });
const wait = (dur) => ({ type: 'wait', dur });
const TAU = Math.PI * 2;

export const STOPS = [
  {
    id: 'uw',
    era: 'past',
    year: '2016',
    label: 'UWaterloo',
    pos: { x: 0, L: -28 },
    title: 'University of Waterloo',
    role: 'BASc, Chemical Engineering + Management Sciences',
    blurb: 'Where it started. Studied reactors, ended up shipping code.',
    bubbles: [
      { text: 'Chem Eng grad who ended up writing code', at: [-4.2, 3.6, -28.3] },
      { text: "Startup Weekend + UW Apprentice '15", at: [3.8, 1.4, -29.5] },
      { text: 'Honk.', at: [2.8, 1.2, -28.2] },
    ],
  },
  {
    id: 'lansa',
    era: 'past',
    year: '2016',
    label: 'LANSA',
    pos: { x: 0, L: -22 },
    title: 'LANSA',
    role: 'Application Developer',
    blurb: 'First real job. Commerce platforms for enterprise clients.',
    bubbles: [{ text: 'First production deploy (gulp)', at: [-4, 3.4, -22.3] }],
    path: hops(0, -28, -22),
  },
  {
    id: 'vidyard',
    era: 'past',
    year: '2017',
    label: 'Vidyard',
    pos: { x: 0, L: -16 },
    title: 'Vidyard',
    role: 'Developer, Professional Services',
    blurb: 'Built custom video integrations for big customers.',
    bubbles: [{ text: 'Integrations for days', at: [3, 2.4, -16] }],
    path: hops(0, -22, -16),
  },
  {
    id: 'asteroidx',
    era: 'past',
    year: '2018',
    label: 'AsteroidX',
    pos: { x: 0, L: -11 },
    title: 'AsteroidX',
    role: 'Lead Software Developer',
    blurb: 'Amazon PPC analytics. Lots of background workers.',
    bubbles: [{ text: '40+ workers crunching ad data', at: [3, 3.2, -11] }],
    path: hops(0, -16, -11),
  },
  {
    id: 'podia',
    era: 'past',
    year: '2019',
    label: 'Podia',
    pos: { x: 0, L: -6 },
    title: 'Podia',
    role: 'Product Developer, then Senior Product Developer',
    blurb: 'Helped creators sell courses, downloads and memberships.',
    bubbles: [{ text: 'Creators first', at: [3, 1.2, -6] }],
    path: hops(0, -11, -6),
  },
  {
    id: 'freshly',
    era: 'now',
    year: '2026',
    label: 'Freshly',
    pos: { x: 0, L: 0 },
    title: 'Freshly Commerce',
    role: 'Co-founder & CTO',
    blurb: 'Simple Bundles, Simple Discounts and Freshly Inventory. Shopify apps powering 20,000+ brands.',
    links: [
      { text: 'See the products', href: 'work/' },
      { text: 'simplebundles.com', href: 'https://www.simplebundles.com/', ext: true },
    ],
    bubbles: [
      { text: 'Co-founder & CTO', at: [-4.6, 3.6, 1.4] },
      { text: 'Glossier, STANLEY, Yamaha and more', at: [3.2, 3.4, 0.3] },
      { text: '20,000+ Shopify brands', at: [6.2, 3.3, 0.3] },
    ],
    path: hops(0, -6, 0),
  },
  {
    id: 'road',
    era: 'future',
    year: '2027',
    label: 'The Road',
    gear: 'shades',
    pos: { x: -0.8, L: 10 },
    title: 'The road ahead',
    role: 'Onward',
    blurb: "Past this point is where I'm headed. Look both ways.",
    bubbles: [
      { text: "The Bronco's warmed up", at: [1, 1.8, 10] },
      { text: 'Look both ways', at: [-2.5, 1.2, 5] },
    ],
    path: [...hops(0, 0, 8), hop(-0.4, 9), hop(-0.8, 10)],
  },
  {
    id: 'roadtrip',
    era: 'future',
    year: '2027',
    label: 'Road trip',
    gear: 'shades',
    pos: { x: -0.2, L: 21 },
    title: 'Road trips in the Bronco',
    role: 'Off-road, on purpose',
    blurb: 'Weekends go to the Bronco. Mud is a feature.',
    bubbles: [
      { text: 'Campfire debugging', at: [-1.5, 1.4, 21.2] },
      { text: '4x4 engaged', at: [1.3, 2.1, 20.6] },
    ],
    path: [
      hop(0.2, 10),
      hop(1, 10),
      mount('bronco'),
      drive(0.2, 13.2, { dur: 1.2, ease: 'in' }),
      drive(0.2, 15.5, { dur: 0.9, bumpy: 0.2, fx: 'mud', ease: 'linear' }),
      jump(0.3, 16.5, { h: 0.5, dur: 0.4, fx: 'mud' }),
      drive(0.2, 18, { dur: 0.7, bumpy: 0.2, fx: 'mud', ease: 'linear' }),
      drive(1.3, 20.6, { dur: 1, ease: 'out', rot: -0.3 }),
      dismount('bronco'),
      hop(0.5, 21),
      hop(-0.2, 21),
    ],
  },
  {
    id: 'surf',
    era: 'future',
    year: '2028',
    label: 'Surf',
    gear: 'shades',
    pos: { x: 0, L: 32 },
    title: 'Chasing waves',
    role: 'Surfing (badly, enthusiastically)',
    blurb: 'Salt water resets everything.',
    bubbles: [
      { text: 'Wipeouts count as R&D', at: [-4, 2.4, 31.6] },
      { text: 'Next: trails', at: [1.2, 1.6, 32.4] },
    ],
    path: [
      ...hops(0, 21, 22),
      hop(0.8, 23),
      mount('surf'),
      drive(0.8, 24.6, { dur: 0.9, ease: 'in', fx: 'splash' }),
      jump(0.4, 26.8, { h: 0.9, dur: 0.8, fx: 'splash' }),
      jump(1.0, 29.0, { h: 1.4, dur: 1.0, spin: TAU, fx: 'splash' }),
      drive(0.8, 31, { dur: 0.9, ease: 'out', fx: 'splash' }),
      dismount('surf'),
      hop(0, 32),
    ],
  },
  {
    id: 'trail',
    era: 'future',
    year: '2029',
    label: 'MTB',
    gear: 'helmet',
    pos: { x: 0, L: 46 },
    title: 'Mountain biking',
    role: 'Sending it',
    blurb: 'Roots, rocks, and the occasional backflip (in my head).',
    bubbles: [
      { text: 'Send it. Then write the postmortem.', at: [0.3, 1.8, 42] },
      { text: 'Next: up the mountain', at: [2.6, 4.6, 46.3] },
    ],
    path: [
      hop(1.2, 32),
      mount('bike'),
      drive(0.3, 35.3, { dur: 1.0, ease: 'in', fx: 'dirt' }),
      jump(0.3, 36.8, { h: 0.8, dur: 0.5, fx: 'dirt' }),
      drive(0.3, 38.3, { dur: 0.45, ease: 'linear', fx: 'dirt' }),
      jump(0.3, 39.8, { h: 0.8, dur: 0.5, fx: 'dirt' }),
      drive(0.3, 41.9, { dur: 0.6, ease: 'linear', alt: 0.85 }),
      jump(0.3, 45.2, { h: 2.6, dur: 1.3, alt: 0, flip: -TAU, fx: 'dirt' }),
      drive(0.8, 45.8, { dur: 0.5, ease: 'out' }),
      dismount('bike'),
      hop(0, 46),
    ],
  },
  {
    id: 'lift',
    era: 'future',
    year: '2030',
    label: 'Snow',
    gear: 'beanie',
    pos: { x: 0, L: 56 },
    title: 'Snowboarding season',
    role: 'Up the $100M mountain',
    blurb: 'The climb is the fun part. Ride the lift, then drop in.',
    bubbles: [
      { text: 'Every season, bigger mountain', at: [-1, 1.6, 56] },
      { text: 'Terrain park ahead', at: [0.4, 1.6, 59] },
    ],
    path: [
      hop(1.2, 46),
      hop(2.3, 46),
      mount('chair'),
      drive(2.3, 46.2, { dur: 0.5, alt: 1.9, ease: 'inout' }),
      drive(2.3, 55.8, { dur: 4, alt: 1.9, ease: 'linear' }),
      drive(2.3, 56.2, { dur: 0.5, alt: 0, ease: 'inout' }),
      dismount('chair'),
      hop(1.2, 56),
      hop(0, 56),
    ],
  },
  {
    id: 'park',
    era: 'future',
    year: '2031',
    label: 'Park',
    gear: 'beanie',
    pos: { x: 0, L: 65.8 },
    title: 'The terrain park',
    role: 'Shipping > perfect',
    blurb: 'Small jumps, then bigger ones. Same as building a company.',
    bubbles: [{ text: '720 (in my dreams)', at: [0.4, 2.2, 64] }],
    path: [
      hop(0.8, 56),
      mount('board'),
      drive(0.4, 58.3, { dur: 0.8, ease: 'in', fx: 'snow', rot: 0.5 }),
      jump(0.4, 59.9, { h: 1.1, dur: 0.7, spin: TAU, fx: 'snow' }),
      drive(0.4, 61.4, { dur: 0.5, ease: 'linear', fx: 'snow' }),
      jump(0.4, 62.9, { h: 1.1, dur: 0.7, spin: -TAU, fx: 'snow' }),
      drive(0.4, 64.2, { dur: 0.45, ease: 'linear', alt: 0.75 }),
      jump(0.4, 65.8, { h: 2.4, dur: 1.2, alt: 0, spin: TAU * 2, fx: 'snow' }),
      dismount('board'),
      hop(0, 65.8),
    ],
  },
  {
    id: 'summit',
    era: 'future',
    year: '20XX',
    label: '$100M',
    gear: 'beanie',
    pos: { x: 0, L: 72 },
    title: 'The $100M summit',
    role: 'Where Freshly is headed',
    blurb: 'Building Freshly Commerce into a $100M company. Still climbing.',
    links: [{ text: 'Freshly Commerce', href: 'https://www.freshlycommerce.com/', ext: true }],
    bubbles: [
      { text: '$100M or bust', at: [-1.1, 4.2, 72.2] },
      { text: 'One more thing', at: [2.6, 5, 73] },
    ],
    path: [hop(0, 66), ...hops(0, 66, 72)],
  },
  {
    id: 'launch',
    era: 'future',
    year: '???',
    label: 'Launch',
    gear: 'suit',
    pos: { x: 2.6, L: 73, alt: 40 },
    title: "What's next?",
    role: "Let's build it together",
    blurb: 'Building something in commerce, or want to trade trail recs? Say hi.',
    links: [
      { text: 'Contact me', href: 'contact/' },
      { text: 'Read my thoughts', href: 'thoughts/' },
    ],
    bubbles: [],
    path: [
      hop(1.3, 72.5),
      hop(2.6, 73),
      mount('rocket'),
      wait(0.9),
      { type: 'move', x: 2.6, L: 73, alt: 40, dur: 3.6, ease: 'in', fx: 'flame' },
    ],
  },
];

export const START = STOPS.findIndex((s) => s.id === 'freshly');
